### ISSUE TITLE
onSaveInstanceState//retain

### ISSUE THREAD

**Issue by neikila** [nexterot/technopark-android-homework#1]
Интересная идея воспользоваться retainFragment'ом. 
Однако реализовано неверно, проверяешь фрагмент по id. По id - верстки. При пересоздании активити ты потеряешь всею верстку. Я проверил, твой фрагмент действительно все еще существует, но создаешь новый. 
Таким образом у тебя бага формата:
свернуть приложение.
Запустить ютуб, чтобы системе потребовалось много памяти, вынудив убить твою активити.
Развернуть приложение (оно все еще будет в списке запущенных задач).
Чтобы повторить это наверняка без запуска сторонних приложений, необходимо в настройках разработчика внизу отыскать функцию "Dont keep activities" или на русском иногад переведено как "Не сохранять операции".

Если ты воспользовался бы onSaveInstanceState этого бы не было так как ты данные бы сериализовались и дожидались бы разворота.
Также бы не было если бы ты достал свой fragment по например тегу, как это указано в доке.

Либо переделай на retain, чтобы действительно доставался твой фрагмент, либо через saveInstanceState.

**Comment by nexterot** [comment]
Включил "Не сохранять операции". Судя по всему, setRetainInstance(true) не предотвращает смерть фрагмента при смерти процесса (видно при логгировании onCreate/onDestroy), поэтому в итоге использовал saveInstanceState.
