### ISSUE TITLE
Неправильное взаимодействие Fragment -> Activity 

### ISSUE THREAD

**Issue by neikila** [nexterot/technopark-android-homework#2]
В обработке клика ты напрямую работаешь с версткой активити.
Ты внутри фрагмента работаешь с тем, что должно находится в отвественности активити и только её.
Таким образом ты например лишаешь нас возможности сделать, чтобы список и выбранное число в планшете работали без смены экранов, без необходимости редактировать фрагменты.

Не следует внутри фрагмента делать предположения о том, как именно работает активити и какая у неё верстка.

На лекциях был показан способ как надо взаимодействовать с активити:
нужно выделить интерфейс на стороне фрагмента, в котором определить метод: onNumSelected(num, color). 
Реализовать его со стороны активити.
и в онклике вызвать его.
Активити сама примет решение о том,что надо создать фрагмент и поместить его в нужное место.

**Comment by nexterot** [comment]
Исправил.
